<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wwwroot\Images\Albums\1.jpg" />
    <None Remove="wwwroot\Images\Albums\10.jpg" />
    <None Remove="wwwroot\Images\Albums\100.jpg" />
    <None Remove="wwwroot\Images\Albums\102.jpg" />
    <None Remove="wwwroot\Images\Albums\104.jpg" />
    <None Remove="wwwroot\Images\Albums\105.jpg" />
    <None Remove="wwwroot\Images\Albums\106.jpg" />
    <None Remove="wwwroot\Images\Albums\107.jpg" />
    <None Remove="wwwroot\Images\Albums\109.jpg" />
    <None Remove="wwwroot\Images\Albums\112.jpg" />
    <None Remove="wwwroot\Images\Albums\113.jpg" />
    <None Remove="wwwroot\Images\Albums\114.jpg" />
    <None Remove="wwwroot\Images\Albums\119.jpg" />
    <None Remove="wwwroot\Images\Albums\120.jpg" />
    <None Remove="wwwroot\Images\Albums\121.jpg" />
    <None Remove="wwwroot\Images\Albums\122.jpg" />
    <None Remove="wwwroot\Images\Albums\124.jpg" />
    <None Remove="wwwroot\Images\Albums\125.jpg" />
    <None Remove="wwwroot\Images\Albums\126.jpg" />
    <None Remove="wwwroot\Images\Albums\127.jpg" />
    <None Remove="wwwroot\Images\Albums\128.jpg" />
    <None Remove="wwwroot\Images\Albums\130.jpg" />
    <None Remove="wwwroot\Images\Albums\132.jpg" />
    <None Remove="wwwroot\Images\Albums\135.jpg" />
    <None Remove="wwwroot\Images\Albums\136.jpg" />
    <None Remove="wwwroot\Images\Albums\137.jpg" />
    <None Remove="wwwroot\Images\Albums\138.jpg" />
    <None Remove="wwwroot\Images\Albums\14.jpg" />
    <None Remove="wwwroot\Images\Albums\140.jpg" />
    <None Remove="wwwroot\Images\Albums\141.jpg" />
    <None Remove="wwwroot\Images\Albums\142.jpg" />
    <None Remove="wwwroot\Images\Albums\143.jpg" />
    <None Remove="wwwroot\Images\Albums\144.jpg" />
    <None Remove="wwwroot\Images\Albums\145.jpg" />
    <None Remove="wwwroot\Images\Albums\146.jpg" />
    <None Remove="wwwroot\Images\Albums\147.jpg" />
    <None Remove="wwwroot\Images\Albums\152.jpg" />
    <None Remove="wwwroot\Images\Albums\154.jpg" />
    <None Remove="wwwroot\Images\Albums\156.jpg" />
    <None Remove="wwwroot\Images\Albums\157.jpg" />
    <None Remove="wwwroot\Images\Albums\158.jpg" />
    <None Remove="wwwroot\Images\Albums\159.jpg" />
    <None Remove="wwwroot\Images\Albums\16.jpg" />
    <None Remove="wwwroot\Images\Albums\160.jpg" />
    <None Remove="wwwroot\Images\Albums\161.jpg" />
    <None Remove="wwwroot\Images\Albums\162.jpg" />
    <None Remove="wwwroot\Images\Albums\163.jpg" />
    <None Remove="wwwroot\Images\Albums\164.jpg" />
    <None Remove="wwwroot\Images\Albums\165.jpg" />
    <None Remove="wwwroot\Images\Albums\166.jpg" />
    <None Remove="wwwroot\Images\Albums\167.jpg" />
    <None Remove="wwwroot\Images\Albums\170.jpg" />
    <None Remove="wwwroot\Images\Albums\171.jpg" />
    <None Remove="wwwroot\Images\Albums\172.jpg" />
    <None Remove="wwwroot\Images\Albums\173.jpg" />
    <None Remove="wwwroot\Images\Albums\174.jpg" />
    <None Remove="wwwroot\Images\Albums\175.jpg" />
    <None Remove="wwwroot\Images\Albums\177.jpg" />
    <None Remove="wwwroot\Images\Albums\178.jpg" />
    <None Remove="wwwroot\Images\Albums\179.jpg" />
    <None Remove="wwwroot\Images\Albums\18.jpg" />
    <None Remove="wwwroot\Images\Albums\180.jpg" />
    <None Remove="wwwroot\Images\Albums\181.jpg" />
    <None Remove="wwwroot\Images\Albums\182.jpg" />
    <None Remove="wwwroot\Images\Albums\183.jpg" />
    <None Remove="wwwroot\Images\Albums\184.jpg" />
    <None Remove="wwwroot\Images\Albums\186.jpg" />
    <None Remove="wwwroot\Images\Albums\187.jpg" />
    <None Remove="wwwroot\Images\Albums\189.jpg" />
    <None Remove="wwwroot\Images\Albums\19.jpg" />
    <None Remove="wwwroot\Images\Albums\190.jpg" />
    <None Remove="wwwroot\Images\Albums\191.jpg" />
    <None Remove="wwwroot\Images\Albums\194.jpg" />
    <None Remove="wwwroot\Images\Albums\195.jpg" />
    <None Remove="wwwroot\Images\Albums\198.jpg" />
    <None Remove="wwwroot\Images\Albums\199.jpg" />
    <None Remove="wwwroot\Images\Albums\2.jpg" />
    <None Remove="wwwroot\Images\Albums\20.jpg" />
    <None Remove="wwwroot\Images\Albums\201.jpg" />
    <None Remove="wwwroot\Images\Albums\202.jpg" />
    <None Remove="wwwroot\Images\Albums\203.jpg" />
    <None Remove="wwwroot\Images\Albums\204.jpg" />
    <None Remove="wwwroot\Images\Albums\205.jpg" />
    <None Remove="wwwroot\Images\Albums\206.jpg" />
    <None Remove="wwwroot\Images\Albums\207.jpg" />
    <None Remove="wwwroot\Images\Albums\208.jpg" />
    <None Remove="wwwroot\Images\Albums\21.jpg" />
    <None Remove="wwwroot\Images\Albums\210.jpg" />
    <None Remove="wwwroot\Images\Albums\211.jpg" />
    <None Remove="wwwroot\Images\Albums\212.jpg" />
    <None Remove="wwwroot\Images\Albums\213.jpg" />
    <None Remove="wwwroot\Images\Albums\218.jpg" />
    <None Remove="wwwroot\Images\Albums\219.jpg" />
    <None Remove="wwwroot\Images\Albums\22.jpg" />
    <None Remove="wwwroot\Images\Albums\220.jpg" />
    <None Remove="wwwroot\Images\Albums\221.jpg" />
    <None Remove="wwwroot\Images\Albums\222.jpg" />
    <None Remove="wwwroot\Images\Albums\225.jpg" />
    <None Remove="wwwroot\Images\Albums\226.jpg" />
    <None Remove="wwwroot\Images\Albums\230.jpg" />
    <None Remove="wwwroot\Images\Albums\231.jpg" />
    <None Remove="wwwroot\Images\Albums\232.jpg" />
    <None Remove="wwwroot\Images\Albums\233.jpg" />
    <None Remove="wwwroot\Images\Albums\234.jpg" />
    <None Remove="wwwroot\Images\Albums\236.jpg" />
    <None Remove="wwwroot\Images\Albums\237.jpg" />
    <None Remove="wwwroot\Images\Albums\238.jpg" />
    <None Remove="wwwroot\Images\Albums\24.jpg" />
    <None Remove="wwwroot\Images\Albums\240.jpg" />
    <None Remove="wwwroot\Images\Albums\241.jpg" />
    <None Remove="wwwroot\Images\Albums\242.jpg" />
    <None Remove="wwwroot\Images\Albums\244.jpg" />
    <None Remove="wwwroot\Images\Albums\247.jpg" />
    <None Remove="wwwroot\Images\Albums\248.jpg" />
    <None Remove="wwwroot\Images\Albums\249.jpg" />
    <None Remove="wwwroot\Images\Albums\25.jpg" />
    <None Remove="wwwroot\Images\Albums\251.jpg" />
    <None Remove="wwwroot\Images\Albums\252.jpg" />
    <None Remove="wwwroot\Images\Albums\253.jpg" />
    <None Remove="wwwroot\Images\Albums\254.jpg" />
    <None Remove="wwwroot\Images\Albums\255.jpg" />
    <None Remove="wwwroot\Images\Albums\256.jpg" />
    <None Remove="wwwroot\Images\Albums\257.jpg" />
    <None Remove="wwwroot\Images\Albums\258.jpg" />
    <None Remove="wwwroot\Images\Albums\26.jpg" />
    <None Remove="wwwroot\Images\Albums\260.jpg" />
    <None Remove="wwwroot\Images\Albums\261.jpg" />
    <None Remove="wwwroot\Images\Albums\263.jpg" />
    <None Remove="wwwroot\Images\Albums\264.jpg" />
    <None Remove="wwwroot\Images\Albums\265.jpg" />
    <None Remove="wwwroot\Images\Albums\266.jpg" />
    <None Remove="wwwroot\Images\Albums\269.jpg" />
    <None Remove="wwwroot\Images\Albums\27.jpg" />
    <None Remove="wwwroot\Images\Albums\271.jpg" />
    <None Remove="wwwroot\Images\Albums\272.jpg" />
    <None Remove="wwwroot\Images\Albums\273.jpg" />
    <None Remove="wwwroot\Images\Albums\275.jpg" />
    <None Remove="wwwroot\Images\Albums\276.jpg" />
    <None Remove="wwwroot\Images\Albums\28.jpg" />
    <None Remove="wwwroot\Images\Albums\280.jpg" />
    <None Remove="wwwroot\Images\Albums\281.jpg" />
    <None Remove="wwwroot\Images\Albums\282.jpg" />
    <None Remove="wwwroot\Images\Albums\284.jpg" />
    <None Remove="wwwroot\Images\Albums\285.jpg" />
    <None Remove="wwwroot\Images\Albums\286.jpg" />
    <None Remove="wwwroot\Images\Albums\287.jpg" />
    <None Remove="wwwroot\Images\Albums\288.jpg" />
    <None Remove="wwwroot\Images\Albums\289.jpg" />
    <None Remove="wwwroot\Images\Albums\29.jpg" />
    <None Remove="wwwroot\Images\Albums\291.jpg" />
    <None Remove="wwwroot\Images\Albums\292.jpg" />
    <None Remove="wwwroot\Images\Albums\293.jpg" />
    <None Remove="wwwroot\Images\Albums\294.jpg" />
    <None Remove="wwwroot\Images\Albums\295.jpg" />
    <None Remove="wwwroot\Images\Albums\298.jpg" />
    <None Remove="wwwroot\Images\Albums\299.jpg" />
    <None Remove="wwwroot\Images\Albums\3.jpg" />
    <None Remove="wwwroot\Images\Albums\30.jpg" />
    <None Remove="wwwroot\Images\Albums\300.jpg" />
    <None Remove="wwwroot\Images\Albums\301.jpg" />
    <None Remove="wwwroot\Images\Albums\304.jpg" />
    <None Remove="wwwroot\Images\Albums\305.jpg" />
    <None Remove="wwwroot\Images\Albums\306.jpg" />
    <None Remove="wwwroot\Images\Albums\307.jpg" />
    <None Remove="wwwroot\Images\Albums\308.jpg" />
    <None Remove="wwwroot\Images\Albums\309.jpg" />
    <None Remove="wwwroot\Images\Albums\31.jpg" />
    <None Remove="wwwroot\Images\Albums\311.jpg" />
    <None Remove="wwwroot\Images\Albums\312.jpg" />
    <None Remove="wwwroot\Images\Albums\313.jpg" />
    <None Remove="wwwroot\Images\Albums\314.jpg" />
    <None Remove="wwwroot\Images\Albums\315.jpg" />
    <None Remove="wwwroot\Images\Albums\316.jpg" />
    <None Remove="wwwroot\Images\Albums\317.jpg" />
    <None Remove="wwwroot\Images\Albums\318.jpg" />
    <None Remove="wwwroot\Images\Albums\319.jpg" />
    <None Remove="wwwroot\Images\Albums\32.jpg" />
    <None Remove="wwwroot\Images\Albums\320.jpg" />
    <None Remove="wwwroot\Images\Albums\322.jpg" />
    <None Remove="wwwroot\Images\Albums\323.jpg" />
    <None Remove="wwwroot\Images\Albums\325.jpg" />
    <None Remove="wwwroot\Images\Albums\327.jpg" />
    <None Remove="wwwroot\Images\Albums\328.jpg" />
    <None Remove="wwwroot\Images\Albums\33.jpg" />
    <None Remove="wwwroot\Images\Albums\330.jpg" />
    <None Remove="wwwroot\Images\Albums\331.jpg" />
    <None Remove="wwwroot\Images\Albums\332.jpg" />
    <None Remove="wwwroot\Images\Albums\333.jpg" />
    <None Remove="wwwroot\Images\Albums\334.jpg" />
    <None Remove="wwwroot\Images\Albums\337.jpg" />
    <None Remove="wwwroot\Images\Albums\34.jpg" />
    <None Remove="wwwroot\Images\Albums\340.jpg" />
    <None Remove="wwwroot\Images\Albums\343.jpg" />
    <None Remove="wwwroot\Images\Albums\344.jpg" />
    <None Remove="wwwroot\Images\Albums\347.jpg" />
    <None Remove="wwwroot\Images\Albums\348.jpg" />
    <None Remove="wwwroot\Images\Albums\349.jpg" />
    <None Remove="wwwroot\Images\Albums\35.jpg" />
    <None Remove="wwwroot\Images\Albums\351.jpg" />
    <None Remove="wwwroot\Images\Albums\352.jpg" />
    <None Remove="wwwroot\Images\Albums\354.jpg" />
    <None Remove="wwwroot\Images\Albums\355.jpg" />
    <None Remove="wwwroot\Images\Albums\356.jpg" />
    <None Remove="wwwroot\Images\Albums\360.jpg" />
    <None Remove="wwwroot\Images\Albums\361.jpg" />
    <None Remove="wwwroot\Images\Albums\362.jpg" />
    <None Remove="wwwroot\Images\Albums\364.jpg" />
    <None Remove="wwwroot\Images\Albums\365.jpg" />
    <None Remove="wwwroot\Images\Albums\366.jpg" />
    <None Remove="wwwroot\Images\Albums\367.jpg" />
    <None Remove="wwwroot\Images\Albums\368.jpg" />
    <None Remove="wwwroot\Images\Albums\37.jpg" />
    <None Remove="wwwroot\Images\Albums\370.jpg" />
    <None Remove="wwwroot\Images\Albums\372.jpg" />
    <None Remove="wwwroot\Images\Albums\374.jpg" />
    <None Remove="wwwroot\Images\Albums\375.jpg" />
    <None Remove="wwwroot\Images\Albums\376.jpg" />
    <None Remove="wwwroot\Images\Albums\377.jpg" />
    <None Remove="wwwroot\Images\Albums\379.jpg" />
    <None Remove="wwwroot\Images\Albums\38.jpg" />
    <None Remove="wwwroot\Images\Albums\380.jpg" />
    <None Remove="wwwroot\Images\Albums\381.jpg" />
    <None Remove="wwwroot\Images\Albums\382.jpg" />
    <None Remove="wwwroot\Images\Albums\383.jpg" />
    <None Remove="wwwroot\Images\Albums\384.jpg" />
    <None Remove="wwwroot\Images\Albums\385.jpg" />
    <None Remove="wwwroot\Images\Albums\386.jpg" />
    <None Remove="wwwroot\Images\Albums\387.jpg" />
    <None Remove="wwwroot\Images\Albums\389.jpg" />
    <None Remove="wwwroot\Images\Albums\39.jpg" />
    <None Remove="wwwroot\Images\Albums\390.jpg" />
    <None Remove="wwwroot\Images\Albums\391.jpg" />
    <None Remove="wwwroot\Images\Albums\392.jpg" />
    <None Remove="wwwroot\Images\Albums\394.jpg" />
    <None Remove="wwwroot\Images\Albums\395.jpg" />
    <None Remove="wwwroot\Images\Albums\396.jpg" />
    <None Remove="wwwroot\Images\Albums\397.jpg" />
    <None Remove="wwwroot\Images\Albums\399.jpg" />
    <None Remove="wwwroot\Images\Albums\4.jpg" />
    <None Remove="wwwroot\Images\Albums\400.jpg" />
    <None Remove="wwwroot\Images\Albums\401.jpg" />
    <None Remove="wwwroot\Images\Albums\402.jpg" />
    <None Remove="wwwroot\Images\Albums\403.jpg" />
    <None Remove="wwwroot\Images\Albums\404.jpg" />
    <None Remove="wwwroot\Images\Albums\405.jpg" />
    <None Remove="wwwroot\Images\Albums\406.jpg" />
    <None Remove="wwwroot\Images\Albums\408.jpg" />
    <None Remove="wwwroot\Images\Albums\41.jpg" />
    <None Remove="wwwroot\Images\Albums\410.jpg" />
    <None Remove="wwwroot\Images\Albums\412.jpg" />
    <None Remove="wwwroot\Images\Albums\413.jpg" />
    <None Remove="wwwroot\Images\Albums\414.jpg" />
    <None Remove="wwwroot\Images\Albums\415.jpg" />
    <None Remove="wwwroot\Images\Albums\42.jpg" />
    <None Remove="wwwroot\Images\Albums\420.jpg" />
    <None Remove="wwwroot\Images\Albums\421.jpg" />
    <None Remove="wwwroot\Images\Albums\424.jpg" />
    <None Remove="wwwroot\Images\Albums\425.jpg" />
    <None Remove="wwwroot\Images\Albums\426.jpg" />
    <None Remove="wwwroot\Images\Albums\427.jpg" />
    <None Remove="wwwroot\Images\Albums\428.jpg" />
    <None Remove="wwwroot\Images\Albums\429.jpg" />
    <None Remove="wwwroot\Images\Albums\430.jpg" />
    <None Remove="wwwroot\Images\Albums\431.jpg" />
    <None Remove="wwwroot\Images\Albums\432.jpg" />
    <None Remove="wwwroot\Images\Albums\433.jpg" />
    <None Remove="wwwroot\Images\Albums\434.jpg" />
    <None Remove="wwwroot\Images\Albums\435.jpg" />
    <None Remove="wwwroot\Images\Albums\437.jpg" />
    <None Remove="wwwroot\Images\Albums\439.jpg" />
    <None Remove="wwwroot\Images\Albums\44.jpg" />
    <None Remove="wwwroot\Images\Albums\440.jpg" />
    <None Remove="wwwroot\Images\Albums\442.jpg" />
    <None Remove="wwwroot\Images\Albums\443.jpg" />
    <None Remove="wwwroot\Images\Albums\444.jpg" />
    <None Remove="wwwroot\Images\Albums\445.jpg" />
    <None Remove="wwwroot\Images\Albums\446.jpg" />
    <None Remove="wwwroot\Images\Albums\447.jpg" />
    <None Remove="wwwroot\Images\Albums\448.jpg" />
    <None Remove="wwwroot\Images\Albums\449.jpg" />
    <None Remove="wwwroot\Images\Albums\45.jpg" />
    <None Remove="wwwroot\Images\Albums\450.jpg" />
    <None Remove="wwwroot\Images\Albums\452.jpg" />
    <None Remove="wwwroot\Images\Albums\453.jpg" />
    <None Remove="wwwroot\Images\Albums\455.jpg" />
    <None Remove="wwwroot\Images\Albums\457.jpg" />
    <None Remove="wwwroot\Images\Albums\459.jpg" />
    <None Remove="wwwroot\Images\Albums\46.jpg" />
    <None Remove="wwwroot\Images\Albums\461.jpg" />
    <None Remove="wwwroot\Images\Albums\462.jpg" />
    <None Remove="wwwroot\Images\Albums\47.jpg" />
    <None Remove="wwwroot\Images\Albums\5.jpg" />
    <None Remove="wwwroot\Images\Albums\50.jpg" />
    <None Remove="wwwroot\Images\Albums\51.jpg" />
    <None Remove="wwwroot\Images\Albums\53.jpg" />
    <None Remove="wwwroot\Images\Albums\54.jpg" />
    <None Remove="wwwroot\Images\Albums\55.jpg" />
    <None Remove="wwwroot\Images\Albums\56.jpg" />
    <None Remove="wwwroot\Images\Albums\57.jpg" />
    <None Remove="wwwroot\Images\Albums\58.jpg" />
    <None Remove="wwwroot\Images\Albums\59.jpg" />
    <None Remove="wwwroot\Images\Albums\6.jpg" />
    <None Remove="wwwroot\Images\Albums\61.jpg" />
    <None Remove="wwwroot\Images\Albums\63.jpg" />
    <None Remove="wwwroot\Images\Albums\64.jpg" />
    <None Remove="wwwroot\Images\Albums\65.jpg" />
    <None Remove="wwwroot\Images\Albums\66.jpg" />
    <None Remove="wwwroot\Images\Albums\67.jpg" />
    <None Remove="wwwroot\Images\Albums\7.jpg" />
    <None Remove="wwwroot\Images\Albums\70.jpg" />
    <None Remove="wwwroot\Images\Albums\71.jpg" />
    <None Remove="wwwroot\Images\Albums\72.jpg" />
    <None Remove="wwwroot\Images\Albums\73.jpg" />
    <None Remove="wwwroot\Images\Albums\74.jpg" />
    <None Remove="wwwroot\Images\Albums\76.jpg" />
    <None Remove="wwwroot\Images\Albums\78.jpg" />
    <None Remove="wwwroot\Images\Albums\79.jpg" />
    <None Remove="wwwroot\Images\Albums\8.jpg" />
    <None Remove="wwwroot\Images\Albums\80.jpg" />
    <None Remove="wwwroot\Images\Albums\84.jpg" />
    <None Remove="wwwroot\Images\Albums\85.jpg" />
    <None Remove="wwwroot\Images\Albums\87.jpg" />
    <None Remove="wwwroot\Images\Albums\88.jpg" />
    <None Remove="wwwroot\Images\Albums\89.jpg" />
    <None Remove="wwwroot\Images\Albums\9.jpg" />
    <None Remove="wwwroot\Images\Albums\90.jpg" />
    <None Remove="wwwroot\Images\Albums\91.jpg" />
    <None Remove="wwwroot\Images\Albums\92.jpg" />
    <None Remove="wwwroot\Images\Albums\93.jpg" />
    <None Remove="wwwroot\Images\Albums\94.jpg" />
    <None Remove="wwwroot\Images\Albums\95.jpg" />
    <None Remove="wwwroot\Images\Albums\96.jpg" />
    <None Remove="wwwroot\Images\Albums\99.jpg" />
    <None Remove="wwwroot\Images\home-showcase.png" />
    <None Remove="wwwroot\Images\logo.png" />
    <None Remove="wwwroot\Images\logo.svg" />
    <None Remove="wwwroot\Images\placeholder.png" />
    <None Remove="wwwroot\Images\placeholder.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="1.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="9.0.0-rc.2.24474.1" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="2.1.175" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
  </ItemGroup>

</Project>
