<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wwwroot\Images\Albums\*.jpg" />
    <None Remove="wwwroot\Images\home-showcase.png" />
    <None Remove="wwwroot\Images\logo.png" />
    <None Remove="wwwroot\Images\logo.svg" />
    <None Remove="wwwroot\Images\placeholder.png" />
    <None Remove="wwwroot\Images\placeholder.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="1.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="9.0.0-rc.2.24474.1" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="2.1.175" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
  </ItemGroup>

</Project>
